### PR TITLE
ATT-32, do not attach to active visit when no encounter is specified

### PR DESCRIPTION
**Pull request by cioan**
Hi @mseaton, here is the PR to fix this bug. We should also open a separate ticket for configuring the module to work in both modes, visit-less and automatically attach to current visit?

### CODE REVIEW

**Review by mseaton — COMMENTED** [review]
@cioan I'm curious what @mks-d and @mogoodrich think.  My main concern is that this particular fix may lead to unexpected behavior by a consuming client.  If a client passes in a non-null visit, and this completes without throwing any exceptions, then that client will reasonably assume that the attachment was successfully saved and associated with the visit they passed in.

My personal preference would be to throw an exception if a non-null visit is passed in, and the default encounter type property is not set.  Then, it should be the responsibility of the code that is calling this method to determine whether or not to pass the visit into it.  @mks-d how did you intend for this to work?

**Comment by mseaton** [comment]
Also, @cioan you'll likely want to squash your commits before merging.

**Review by mks-d — COMMENTED** [review]
First of all I would step back because you shouldn't be using this deprecated controller. See my comment [here](https://issues.openmrs.org/browse/ATT-32?focusedCommentId=259369&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-259369).

**Review by mks-d — COMMENTED** [review]
First of all I would step back because you shouldn't be using this deprecated controller. See my comment [here](https://issues.openmrs.org/browse/ATT-32?focusedCommentId=259369&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-259369).

**Pull request closed without merging**
